name: Docker Image CI
on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. 1.0, 20.15.10
jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: github_ref
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/386
          tags: |
            dmitter/hello-http-world:latest
            dmitter/hello-http-world:${{ steps.github_ref.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
