name: Docker Image CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: arm64v8
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dmitter/hello-http-world
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.arm64v8
